# Generated by Django 4.0.5 on 2022-08-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_block_flow_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='bot.block', verbose_name='Блок'),
        ),
    ]
