# Generated by Django 4.0.5 on 2022-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_flow_presentation_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='id_telegram',
            field=models.IntegerField(verbose_name='Id telegram'),
        ),
    ]
