# Generated by Django 4.0.5 on 2022-08-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_speaker_id_telegram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='Flow_group',
            new_name='flow_group',
        ),
    ]
