# Generated by Django 4.0.5 on 2022-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_rename_flow_group_block_flow_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок выступлений/перерывров', 'verbose_name_plural': 'Блоки выступлений/перерывов'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='flow_group',
            options={'verbose_name': 'Группа блоков по времени', 'verbose_name_plural': 'Группы блоков по времени'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Презентация', 'verbose_name_plural': 'Презантации'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'Спикер/организатор', 'verbose_name_plural': 'Спикеры/организаторы'},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='presentations', to='bot.speaker', verbose_name='Спикер'),
        ),
    ]
