# Generated by Django 4.0.5 on 2022-08-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_block_options_alter_flow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'блок выступлений/перерыв', 'verbose_name_plural': 'Блоки выступлений/перерывы'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': 'мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='flow_group',
            options={'verbose_name': 'группу блоков по времени', 'verbose_name_plural': 'Группы блоков по времени'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'презентацию', 'verbose_name_plural': 'Презантации'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'спикера/организатора', 'verbose_name_plural': 'Спикеры/организаторы'},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='Presentations', to='bot.speaker', verbose_name='Спикер'),
        ),
    ]
